"""add_daily_report_settings

Revision ID: 2d0585acae84
Revises: eaf5a95d155f
Create Date: 2026-07-13 00:13:32.702930

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d0585acae84"
down_revision: str | Sequence[str] | None = "eaf5a95d155f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "daily_report_enabled", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    op.add_column(
        "users", sa.Column("daily_calorie_target", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "daily_calorie_target")
    op.drop_column("users", "daily_report_enabled")
    # ### end Alembic commands ###
