"""add_daily_report_time

Revision ID: 2e4ae1dbd023
Revises: 2d0585acae84
Create Date: 2026-07-13 00:25:34.740470

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e4ae1dbd023"
down_revision: str | Sequence[str] | None = "2d0585acae84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "daily_report_time",
            sa.Time(),
            server_default=sa.text("'01:00:00'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "daily_report_time")
    # ### end Alembic commands ###
