"""add_diabetes_mode_and_make_nullable

Revision ID: c4a1e85331a0
Revises: 90af9772b2b8
Create Date: 2026-07-08 19:04:27.728389

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4a1e85331a0"
down_revision: str | Sequence[str] | None = "90af9772b2b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "diabetes_mode", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.alter_column(
        "users", "icr", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "users", "isf", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "users",
        "target_bg",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "target_bg",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "users", "isf", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "users", "icr", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.drop_column("users", "diabetes_mode")
    # ### end Alembic commands ###
