"""drop_insulin_type_column

Revision ID: eaf5a95d155f
Revises: c4a1e85331a0
Create Date: 2026-07-08 19:33:21.920013

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eaf5a95d155f"
down_revision: str | Sequence[str] | None = "c4a1e85331a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "insulin_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "insulin_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
