"""'initial baseline'

Revision ID: ed3af4901824
Revises: 
Create Date: 2026-06-30 23:22:28.229559

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ed3af4901824'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
