"""'initial baseline'

Revision ID: ed3af4901824
Revises:
Create Date: 2026-06-30 23:22:28.229559

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ed3af4901824"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
